import type {
  AgentStep,
  GeneratedFile,
  GenerationResult,
  PreviewSchema
} from "./types";

const fallbackTheme = {
  accent: "#2563eb",
  surface: "#f8fafc",
  ink: "#101828"
};

export function createFallbackBuild(rawPrompt: string): GenerationResult {
  const prompt = rawPrompt.trim();
  const title = createProjectTitle(prompt);
  const domain = title === "AI Product Workspace" ? "product team" : title;

  const agentSteps: AgentStep[] = [
    {
      id: "pm",
      role: "PM",
      title: "Define the user journey",
      summary: `Turned the prompt into a focused workflow for ${domain}.`,
      status: "done",
      detail:
        "The MVP keeps one primary workflow, visible progress, and clear next actions."
    },
    {
      id: "architect",
      role: "Architect",
      title: "Choose a compact architecture",
      summary:
        "Selected a single-page app with durable project records and editable preview schema.",
      status: "done",
      detail:
        "The generated app separates data, view sections, and actions so it can be remixed later."
    },
    {
      id: "engineer",
      role: "Engineer",
      title: "Generate interactive UI",
      summary:
        "Created responsive TSX, structured styles, and action handlers for a usable prototype.",
      status: "done",
      detail:
        "The UI includes a hero, metrics, workflow sections, and two user-facing actions."
    },
    {
      id: "qa",
      role: "QA",
      title: "Review delivery quality",
      summary:
        "Checked that the build has real interaction, persistence hooks, and safe fallback behavior.",
      status: "done",
      detail:
        "The result is intentionally small enough to inspect, test, and deploy quickly."
    }
  ];

  const preview: PreviewSchema = {
    theme: fallbackTheme,
    hero: {
      kicker: "Generated by Mini Atoms",
      title,
      subtitle: prompt
        ? `A focused product prototype for: ${prompt}`
        : "Describe an idea and generate a working app blueprint."
    },
    stats: [
      { label: "Agent steps", value: "4", tone: "blue" },
      { label: "Generated files", value: "5", tone: "green" },
      { label: "Ready flows", value: "2", tone: "violet" }
    ],
    sections: [
      {
        title: "Primary workflow",
        body: `Guide ${domain} users from first intent to a concrete next step with a visible, low-friction flow.`
      },
      {
        title: "Persistent workspace",
        body:
          "Save prompts, generated files, timeline notes, and visual edits so every refresh restores context."
      },
      {
        title: "Remix loop",
        body:
          "Treat each change request as a new generation while preserving previous versions for comparison."
      }
    ],
    actions: [
      { label: "Start workflow", kind: "primary" },
      { label: "Save version", kind: "secondary" }
    ]
  };

  const files: GeneratedFile[] = [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: createPageSource(title)
    },
    {
      path: "app/actions.ts",
      language: "ts",
      content:
        "export async function saveProject(input: unknown) {\n  return { ok: true, savedAt: new Date().toISOString(), input };\n}\n"
    },
    {
      path: "lib/preview-schema.ts",
      language: "ts",
      content: `export const preview = ${JSON.stringify(preview, null, 2)};\n`
    },
    {
      path: "README.md",
      language: "md",
      content: `# ${title}\n\nGenerated from: ${prompt || "a blank starter prompt"}\n\nRun the workflow, save a version, and remix the product idea.\n`
    },
    {
      path: "package.json",
      language: "json",
      content: JSON.stringify(
        {
          scripts: {
            dev: "next dev",
            build: "next build"
          },
          dependencies: {
            next: "16.x",
            react: "19.x",
            "react-dom": "19.x"
          }
        },
        null,
        2
      )
    }
  ];

  return {
    title,
    agentSteps,
    files,
    preview,
    source: "fallback"
  };
}

export function extractGenerationResult(text: string): GenerationResult {
  const json = extractJson(text);

  try {
    const parsed = JSON.parse(json) as Partial<GenerationResult>;
    assertGenerationResult(parsed);

    return {
      ...parsed,
      source: "modelscope"
    };
  } catch (error) {
    throw new Error(
      "Model response did not include a valid generation result",
      error instanceof Error ? { cause: error } : undefined
    );
  }
}

function extractJson(text: string): string {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fenced?.[1]) {
    return fenced[1].trim();
  }

  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start >= 0 && end > start) {
    return text.slice(start, end + 1);
  }

  return text;
}

function assertGenerationResult(
  value: Partial<GenerationResult>
): asserts value is GenerationResult {
  if (
    typeof value.title !== "string" ||
    !Array.isArray(value.agentSteps) ||
    !Array.isArray(value.files) ||
    !value.preview ||
    typeof value.preview.hero?.title !== "string" ||
    !Array.isArray(value.preview.sections) ||
    !Array.isArray(value.preview.actions)
  ) {
    throw new Error("Invalid generation result shape");
  }
}

function createProjectTitle(prompt: string): string {
  if (!prompt) {
    return "AI Product Workspace";
  }

  const compact = prompt
    .replace(/[，。,.!！?？]/g, " ")
    .replace(/^(请|帮我|给|为|做|创建|生成|实现)\s*/g, "")
    .replace(/\s+/g, " ")
    .trim();

  const chineseMatch = compact.match(/[\u4e00-\u9fa5A-Za-z0-9\s-]{2,24}/);
  return (chineseMatch?.[0] || compact || "AI Product Workspace").slice(0, 24);
}

function createPageSource(title: string): string {
  return `export default function Page() {
  return (
    <main>
      <h1>${escapeForTemplate(title)}</h1>
      <button type="button">Start workflow</button>
    </main>
  );
}
`;
}

function escapeForTemplate(value: string): string {
  return value.replace(/[{}<>]/g, "");
}
