import { fireEvent, render, screen } from "@testing-library/react";
import React from "react";
import { describe, expect, it } from "vitest";

import { PreviewPane } from "./PreviewPane";
import type { PreviewSchema } from "@/lib/types";

const preview: PreviewSchema = {
  theme: {
    accent: "#2563eb",
    surface: "#ffffff",
    ink: "#101828"
  },
  hero: {
    kicker: "Generated by Mini Atoms",
    title: "Ops Copilot",
    subtitle: "Coordinate operational work"
  },
  stats: [{ label: "Tasks", value: "18", tone: "blue" }],
  sections: [{ title: "Triage", body: "Prioritize incoming work." }],
  actions: [
    { label: "Start workflow", kind: "primary" },
    { label: "Save version", kind: "secondary" }
  ]
};

describe("PreviewPane", () => {
  it("renders the generated preview schema", () => {
    render(<PreviewPane preview={preview} device="desktop" />);

    expect(screen.getByText("Ops Copilot")).toBeInTheDocument();
    expect(screen.getByText("18")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Start workflow" })).toBeInTheDocument();
  });

  it("shows action feedback when a preview action is clicked", async () => {
    render(<PreviewPane preview={preview} device="mobile" />);

    fireEvent.click(screen.getByRole("button", { name: "Save version" }));

    expect(screen.getByText("Last action: Save version")).toBeInTheDocument();
  });
});
